version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_django_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_6_static:/data/static/
      - gis_6_media:/data/media/

  django:
    image: gis_2_django:5
    networks:
      - gis_django_network
    volumes:
      - gis_6_static:/home/gi_6/staticfiles/
      - gis_6_media:/home/gi_6/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
  mariadb:
    image: mariadb:10.5
    networks:
      - gis_django_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  gis_django_network:

volumes:
  gis_6_static:
  gis_6_media:
  gis_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
      external: true
